# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26b79f37547db3221ff147e88692d8f17baef252b01888eacf6895552e531dfcb220fe50104617f7650b5a6c6cb5129f6e463e2620871cb68fc4e2e70506bab2

test:
  secret_key_base: 806eea4d9d5470de503cf774916bef2e616b2852230e6517cc3e4ad0703ceb711d60fced2ef4acb8d5b286003403ac13c0af993fef546c80ebda18ac319afab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
